{#
    Rewrite the surrogate keys stored in the durable incremental `intermediate`
    tables so they match the `dbt_utils.generate_surrogate_key` format the models
    emit. Written for the 2026-07-10 migration off hand-written md5(a || '|' || b),
    but NOT single-use — see idempotency below.

    Runs in place (UPDATE) — it recomputes each key from columns ALREADY in the
    row, so it never touches staging and never loses accumulated history. The key
    expression is generated by `generate_surrogate_key` itself (not hand-typed),
    so a backfilled historic key is byte-identical to what a fresh model build
    produces for the same row.

    IDEMPOTENT — safe to re-run any time. Each key is a pure function of columns
    already in the row, so a second run recomputes the same value it just wrote;
    the result converges rather than drifting. Nothing calls this automatically
    (no DAG step, no hook) — it only fires via an explicit `dbt run-operation`.
    Keep it as the repair tool if keys ever diverge from the models.

    Cost: the UPDATE is unconditional (no WHERE), so every run rewrites every row
    of all five tables. Cheap at current volumes; on much larger tables that means
    dead tuples and a VACUUM, so it isn't free — just correct.

    Column lists mirror each model's own key, using the STORED column names
    (note: int_city_weather_forecast stores `issued_at`, the alias of the model's
    `issued_at_utc` — same value). If a model's key columns ever change, update
    them here too — nothing enforces that link.

    Usage:
        dbt run-operation backfill_surrogate_keys --target staging \
            --profiles-dir C:/Users/Andrej/.dbt
#}
{% macro backfill_surrogate_keys() %}

    {% set targets = [
        (ref('int_city_hourly_weather'),           'city_hour_key',     ['city', "date_trunc('hour', observed_at)"]),
        (ref('int_city_hourly_pollution'),         'city_hour_key',     ['city', "date_trunc('hour', observed_at)"]),
        (ref('int_city_hourly_traffic_flow'),      'city_hour_key',     ['city', "date_trunc('hour', observed_at)"]),
        (ref('int_city_hourly_traffic_incidents'), 'city_incident_key', ['city', 'incident_id', 'observed_at']),
        (ref('int_city_weather_forecast'),         'forecast_key',      ['city', 'forecast_at', 'issued_at']),
    ] %}

    {% for relation, key_col, cols in targets %}
        {% set new_key = dbt_utils.generate_surrogate_key(cols) %}
        {% set update_sql %}
            update {{ relation }}
            set {{ key_col }} = {{ new_key }}
        {% endset %}
        {{ log("Backfilling " ~ key_col ~ " on " ~ relation ~ " ...", info=True) }}
        {% if execute %}
            {% do run_query(update_sql) %}
            {% set n = run_query("select count(*) as n from " ~ relation).columns[0].values()[0] %}
            {{ log("  done — " ~ n ~ " rows now on util-format " ~ key_col, info=True) }}
        {% endif %}
    {% endfor %}

    {{ log("Backfill complete.", info=True) }}

{% endmacro %}
