name: 'smart_city'
version: '1.0.0'
profile: 'smart_city'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  smart_city:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: fail
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts