smart_city:
  outputs:

    staging:                          # PostgreSQL — staging models
      type: postgres
      host: "{{ env_var('SMART_CITY_PG_HOST', 'host.docker.internal') }}"
      port: 5432
      dbname: smart_city
      user: postgres
      pass: "{{ env_var('SMART_CITY_PG_PASSWORD') }}"
      schema: staging
      threads: 4

  target: staging
